version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: remarkableas/circleci-cypress
    steps:
      - checkout
      - run: yarn --ignore-engines
      - run: yarn test
      - run: nohup yarn start &
      - run: yarn cypress:run --spec "cypress/integration/main/main.spec.js" 
