version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: yarn --ignore-engines
      - run: yarn test
      # Cypress dependency
      # Probably can create a new docker image that includes these dependencies
      - run: sudo apt-get install -y libgtk2.0-0
      - run: sudo apt-get install -y libnotify-dev
      - run: sudo apt-get install -y libgconf-2-4 libnss3 libxss1
      - run: sudo sudo apt-get install -y libasound2 xvfb
      - run: yarn cypress:run --spec "cypress/integration/main/main.spec.js" 
