version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: remarkableas/circleci-cypress
    steps:
      - checkout
      - run: 
          name: Install packages
          command: yarn --ignore-engines
      - run: 
          name: Run unit tests
          command: yarn test
      - run: 
          name: Start server
          command: yarn start
          background: true
      - run: 
          name: Run integration tests
          command: yarn cypress:run --spec "cypress/integration/main/main.spec.js" 
