version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'yarn run build'  # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          record: true        # record results on Cypress Dashboard
          parallel: false
          parallelism: 1
          group: 'all tests'  # name this group "all tests" on the dashboard
          start: 'yarn start'  # start server before running tests